customCommands:
  - key: "C"
    context: "files"
    command: "czg"
    output: terminal
# gui:
#   nerdFontsVersion: "3"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
