[window]
padding = { x = 5, y = 0 }
dynamic_padding = true
decorations = "Full"
opacity = 0.95
blur = true
startup_mode = "Maximized"

[font]
normal = { family = "PlemolJP35 Console NF", style = "Regular"}
bold = { family = "PlemolJP35 Console NF", style = "Medium"}
italic = { family = "PlemolJP35 Console NF", style = "Italic"}
bold_italic = { family = "PlemolJP35 Console NF", style = "Medium Italic"}
offset = { x = 0, y = 1 }
size = 10.5

[keyboard]
bindings = [{ key = "Return", mods = "Shift", chars = "\n" }]

[selection]
save_to_clipboard = true

[cursor]
style = "Underline"

# Colors (Base16 Default Dark)
[colors.primary]
background = '#181818'
foreground = '#d8d8d8'

[colors.cursor]
text = '#181818'
cursor = '#d8d8d8'

# Normal colors
[colors.normal]
black   = '#181818'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
# blue    = '#7cafc2'
blue    = '#81a1c1'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#d8d8d8'

# Bright colors
[colors.bright]
black   = '#585858'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#f8f8f8'
